apiVersion: v1
kind: Service
metadata:
  name: kubeapp-service
spec:
  selector:
    app: kubeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110